# pull official base image
FROM python:3.10-slim-bullseye

RUN apt-get update && apt-get install nginx vim -y --no-install-recommends
RUN apt-get install xmlsec1 -y
COPY nginx.default /etc/nginx/sites-available/default
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# copy source and install dependencies
RUN mkdir -p /opt/app
RUN mkdir -p /opt/app/.pip_cache
RUN mkdir -p /opt/app/django_saml
COPY requirements.txt start-server.sh /opt/app/
COPY .pip_cache /opt/app/.pip_cache/
COPY . /opt/app/django_saml/
WORKDIR /opt/app/django_saml
RUN pip install -r requirements.txt --cache-dir /opt/app/.pip_cache
RUN chown -R www-data:www-data /opt/app/django_saml

# start server
EXPOSE 8000
STOPSIGNAL SIGTERM

CMD ["/opt/app/start-server.sh"]
